function q(a,b,f,c){var d=document.createElement("script"),g="callback"+ ++u,p=document.getElementsByTagName("script")[0],e="";if("string"==typeof b)e=b;else if("object"==typeof b)for(var h in b)e+=encodeURIComponent(h)+"="+encodeURIComponent(b[h])+"&";window[g]=function(a){f.call(c,a);window[g]=null;delete window[g];p.parentNode.removeChild(d)};d.type="text/javascript";d.async=!0;d.src=a+"?"+e+"_Serialize=JSON&callback="+g;p.parentNode.appendChild(d)}var u=0;
function v(a){this.q=a.newRequestAction;this.s=a.requestStateAction;this.l=a.faresAction;this.d=null;this.t=a.Route;this.k=a.Duration||1E3;this.m=a.Language||"RU";this.h=a.Currency||"RUB";this.n=a.Limit||100;this.u=a.updateDuration||1E4;this.a=null;a:{a=document.createElement("div");a.innerHTML='<div class="flights"><div class="flights-tabs"></div><div class="flights-content"></div><div class="flights-loading"><div class="flights-loading-bar"></div><div class="flights-loading-percent">0%</div></div></div>';
	if(1==a.childNodes.length&&(a=a.firstChild,1==a.nodeType))break a;a=null}this.b=a;this.f=this.b.getElementsByClassName(x)[0];this.j=this.b.getElementsByClassName(y)[0];this.e=this.b.getElementsByClassName(z)[0];this.o=this.e.getElementsByClassName(A)[0];this.p=this.e.getElementsByClassName(D)[0];E(this)}function E(a){q(a.q,{Route:a.t},a.r,a)}v.prototype.r=function(a){this.d=a.IdSynonym;F(this)};
function F(a){q(a.s,{R:a.d},function(b){b=b.Completed;100==b?this.getData():(G(this,b),setTimeout(function(){F(a)},this.k))},a)}
v.prototype.getData=function(){q(this.l,{L:this.m,C:this.h,Limit:this.n,DebugFullNames:!0,R:this.d},function(a){this.setData(a);a=this.c;for(var b=a.length,f=0,c,d,g=[];f<b;f++)d=a[f].Code,c=H(this.g,d),c.Current=this.a?this.a==d:0==f,c.Total=H(this.c,d).Fares.length,g.push('<a href="javascript:;" class="flights-tab'+(c.Current?"-current":"")+'" data-code="'+c.Code+'">'+c.Name+" ("+c.Total+")</a>");this.f.innerHTML=g.join("");I(this);this.a||(this.a=this.g[0].Code);J(this);K(this);this.e.style.display=
	"none"},this)};v.prototype.setData=function(a){var b=a.References;this.i=b.Airports;this.g=b.Carriers;this.c=a.Airlines};function K(a){setTimeout(function(){E(a)},a.u)}function I(a){a.f.addEventListener("click",function(b){b=b.target;var f=a.f.getElementsByClassName(L)[0],c=b.dataset.code;c&&(a.a=c,f.className=M,b.className=L,J(a))},!1)}
function J(a){for(var b=H(a.c,a.a).Fares,f=b.length,c=0,d,g=[];c<f;c++){var p=d=b[c],e;e=0;var h=",",m=" ",l=d.TotalAmount;e=isNaN(e=Math.abs(e))?2:e;var h=void 0==h?".":h,m=void 0==m?",":m,r=0>l?"-":"",n=parseInt(l=Math.abs(+l||0).toFixed(e),10)+"",t=3<(t=n.length)?t%3:0;e=r+(t?n.substr(0,t)+m:"")+n.substr(t).replace(/(\d{3})(?=\d)/g,"$1"+m)+(e?h+Math.abs(l-n).toFixed(e).slice(2):"");p.Amount=e;d.Currency=a.h;p=d;e=a;h=d.Directions;m=h.length;l=0;r=void 0;for(n=[];l<m;l++){for(var N=r=h[l],O=e,B=
	r.Points,P=B.length,w=0,k=void 0,C=[];w<P;w++)k=B[w],k.Title=H(O.i,k.ArrivalCode).Name,C.push('<div class="flights-info-point">'+k.Title+" ["+k.ArrivalCode+(k.ArrivalTerminal?"-"+k.ArrivalTerminal:"")+(k.DepartureTerminal?"-"+k.DepartureTerminal:"")+"]</div>");N.Direction=C.join('<div class="flights-info-point-arrow"></div>');n.push('<div class="flights-info-direction">'+r.Direction+"</div>")}p.Title=n.join("");g.push('<div class="flights-info" data-id="'+d.Id+'"><div class="flights-info-amount">'+
d.Amount+" "+d.Currency+'</div><div class="flights-info-title">'+d.Title+"</div></div>")}a.j.innerHTML=g.join("")}function G(a,b){a.o.style.width=b+"%";a.p.innerHTML=b+"%"}v.prototype.render=function(a){(a||document.body).appendChild(this.b)};var x="flights-tabs",y="flights-content",z="flights-loading",A="flights-loading-bar",D="flights-loading-percent",M="flights-tab",L="flights-tab-current";function H(a,b){for(var f=a.length,c=0;c<f;c++)if(a[c].Code==b)return a[c];return null}
window.FlightList=v;